org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

termuxX11NdkVersion=26.3.11579264
termuxX11VersionName=1.03.01

org.gradle.java.home=C:/Program Files/Android/openjdk/jdk-21.0.8
